### ISSUE TITLE
Detail roles of engine_interface and common in chapter 5.2

### ISSUE THREAD

**Issue by Masterchef365** [ChatImproVR/The-Book#10]
Needs more explanation, see TODOs

**Comment by MrKangs** [comment]
On top of that, we want to link the technical document (not the book) for each packages and functions within the packages so that the user can have a better understanding on each function in general.

**Comment by Masterchef365** [comment]
> On top of that, we want to link the technical document (not the book) for each packages and functions within the packages so that the user can have a better understanding on each function in general.

Yeah we'll add a link to the API docs when it's hosted
